FROM ubuntu:latest as base
ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install --no-install-recommends -y \
# cross execution
        proot \
        qemu-user \
    && rm -rf /var/lib/apt/lists/*

####################################################
# build aarch64 rootfs
FROM base as chroot
RUN apt-get update && apt-get install --no-install-recommends -y \
# download
        ca-certificates \
        wget \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir /chroot-armv8-a \
    && wget -nv -O - https://partner-images.canonical.com/core/bionic/current/ubuntu-bionic-core-cloudimg-arm64-root.tar.gz \
        | tar -zx -C /chroot-armv8-a/
RUN proot -q qemu-aarch64 -S /chroot-armv8-a apt update \
    && proot -q qemu-aarch64 -S /chroot-armv8-a apt install -y \
        libpcap-dev \
    && rm -rf /chroot-armv8-a/var/lib/apt/lists/*

####################################################
# install cross compilation tool
FROM base as builder
RUN apt-get update && apt-get install --no-install-recommends -y \
# build basics
        build-essential \
        cmake \
        ninja-build \
# cross compilation
        g++-8-aarch64-linux-gnu \
    && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/aarch64-linux-gnu-gcc-8 /usr/bin/aarch64-linux-gnu-gcc \
    && ln -s /usr/bin/aarch64-linux-gnu-g++-8 /usr/bin/aarch64-linux-gnu-g++
COPY --from=chroot /chroot-armv8-a /chroot-armv8-a
